# This is a basic workflow to help you get started with Actions1111

name: CI

on: push

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with black, isort and possibly run tests
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          pip install requests django
          pip install flake8 isort pytest pytest-django
          pip install freezegun
          ls -la
          flake8 .
          isort --check .
          py.test tests
